import { BGMDefinition } from '../../types'

/**
 * Overworld Theme - Cheerful, upbeat adventure theme
 * Key: C major, BPM: 150, 16 bars
 * Bouncy, syncopated melody with a walking bass line
 */
export const overworld: BGMDefinition = {
  bpm: 150,
  loop: true,
  variations: [
    { name: 'FULL',      layers: [true,  true]  },
    { name: 'ADVENTURE', layers: [true,  false] },
    { name: 'MARCH',     layers: [false, true]  },
  ],
  channels: [
    // Melody - Organ (warm adventure theme, Zelda-inspired)
    {
      wave: 'organ',
      label: 'melody',
      volume: 0.3,
      attack: 0.01,
      release: 0.06,
      notes: [
        // Bar 1-2: Gentle rising motif (F major)
        { pitch: 'F4', duration: '4n' },
        { pitch: 'A4', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'D5', duration: '2n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: 'A4', duration: '4n' },
        { pitch: 'F4', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 3-4: Response phrase, stepping up
        { pitch: 'G4', duration: '4n' },
        { pitch: 'Bb4', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '2n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'Bb4', duration: '4n' },
        { pitch: 'A4', duration: '4n' },

        // Bar 5-6: Soaring higher
        { pitch: 'F5', duration: '2n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: 'D5', duration: '4n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: null, duration: '8n' },
        { pitch: 'A4', duration: '8n' },
        { pitch: 'Bb4', duration: '4n' },
        { pitch: 'C5', duration: '4n' },

        // Bar 7-8: Gentle descent, breathing
        { pitch: 'D5', duration: '4n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: 'A4', duration: '2n' },
        { pitch: 'G4', duration: '4n' },
        { pitch: null, duration: '4n' },
        { pitch: null, duration: '2n' },

        // Bar 9-10: Motif return, variation
        { pitch: 'F4', duration: '4n' },
        { pitch: 'A4', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'F5', duration: '2n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'Bb4', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 11-12: Winding path
        { pitch: 'A4', duration: '8n' },
        { pitch: 'Bb4', duration: '8n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: 'D5', duration: '4n' },
        { pitch: 'E5', duration: '2n' },
        { pitch: 'D5', duration: '4n' },
        { pitch: 'C5', duration: '4n' },

        // Bar 13-14: Climax
        { pitch: 'F5', duration: '4n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'D5', duration: '4n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: 'Bb4', duration: '4n' },
        { pitch: 'A4', duration: '4n' },
        { pitch: 'G4', duration: '4n' },
        { pitch: 'F4', duration: '4n' },

        // Bar 15-16: Resolve home
        { pitch: 'A4', duration: '4n' },
        { pitch: 'C5', duration: '4n' },
        { pitch: 'F5', duration: '2n' },
        { pitch: 'F4', duration: '2n' },
        { pitch: null, duration: '2n' },
      ]
    },
    // Bass - Triangle wave
    {
      wave: 'triangle',
      label: 'bass',
      volume: 0.4,
      notes: [
        // Bar 1-2
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 3-4
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'C3', duration: '4n' },
        { pitch: null, duration: '4n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'F2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'F3', duration: '4n' },

        // Bar 5-6
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'F3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'B2', duration: '4n' },

        // Bar 7-8
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'F2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '4n' },

        // Bar 9-10
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 11-12
        { pitch: 'F2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 13-14
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 15-16
        { pitch: 'C3', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'C3', duration: '4n' },
        { pitch: null, duration: '4n' },
        { pitch: 'F2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: null, duration: '8n' },
        { pitch: 'C3', duration: '2n' },
        { pitch: null, duration: '4n' },
      ]
    },
    // Percussion - Noise channel
    {
      wave: 'noise',
      label: 'percussion',
      volume: 0.25,
      notes: [
        // Repeating 2-bar pattern x8 = 16 bars
        // Kick-hat-snare-hat pattern
        { pitch: 'C2', duration: '8n' },  // kick
        { pitch: 'G5', duration: '8n' },  // hat
        { pitch: 'E4', duration: '8n' },  // snare
        { pitch: 'G5', duration: '8n' },  // hat
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },

        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '4n' },
        { pitch: 'E4', duration: '4n' },
      ]
    }
  ]
}
