import { BGMDefinition } from '../../src/types'

/**
 * Battle Theme - Intense, fast-paced combat music
 * Key: E minor, BPM: 180, 16 bars
 * Driving rhythm, rapid arpeggios, urgent melodic lines
 */
export const battle: BGMDefinition = {
  bpm: 180,
  loop: true,
  channels: [
    // Melody - Square wave
    {
      wave: 'square',
      duty: 0.5,
      volume: 0.5,
      notes: [
        // Bar 1-2: Aggressive opening riff
        { pitch: 'E5', duration: '8n' },
        { pitch: 'E5', duration: '16n' },
        { pitch: 'E5', duration: '16n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'B5', duration: '8n' },
        { pitch: 'A5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: null, duration: '8n' },
        { pitch: 'B4', duration: '8n' },

        // Bar 3-4: Rising urgency
        { pitch: 'C5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: 'A5', duration: '4n' },
        { pitch: 'B5', duration: '8n' },
        { pitch: 'A5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 5-6: Call and response
        { pitch: 'E5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'B5', duration: '4n' },
        { pitch: null, duration: '4n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'A5', duration: '4n' },
        { pitch: null, duration: '4n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: 'B5', duration: '4n' },

        // Bar 7-8: Descending power run
        { pitch: 'B5', duration: '8n' },
        { pitch: 'A5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'B4', duration: '8n' },
        { pitch: 'A4', duration: '8n' },
        { pitch: 'B4', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 9-10: Intense repeated note pattern
        { pitch: 'E5', duration: '16n' },
        { pitch: 'E5', duration: '16n' },
        { pitch: 'E5', duration: '16n' },
        { pitch: 'E5', duration: '16n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: 'D5', duration: '16n' },
        { pitch: 'D5', duration: '16n' },
        { pitch: 'D5', duration: '16n' },
        { pitch: 'D5', duration: '16n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'D5', duration: '4n' },

        // Bar 11-12: Climactic phrase
        { pitch: 'C5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '4n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: 'B5', duration: '4n' },
        { pitch: 'C6', duration: '8n' },
        { pitch: 'B5', duration: '8n' },
        { pitch: 'A5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'F#5', duration: '4n' },
        { pitch: 'E5', duration: '4n' },

        // Bar 13-14: Heroic fanfare
        { pitch: 'E5', duration: '4n' },
        { pitch: null, duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: null, duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'B5', duration: '4n' },
        { pitch: 'A5', duration: '4n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: 'E5', duration: '4n' },

        // Bar 15-16: Turnaround
        { pitch: 'D5', duration: '8n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'F#5', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'A5', duration: '8n' },
        { pitch: 'B5', duration: '8n' },
        { pitch: 'G5', duration: '4n' },
        { pitch: 'E5', duration: '8n' },
        { pitch: 'D5', duration: '8n' },
        { pitch: 'C5', duration: '8n' },
        { pitch: 'B4', duration: '8n' },
        { pitch: 'E5', duration: '2n' },
      ]
    },
    // Bass - Triangle wave (driving pulse)
    {
      wave: 'triangle',
      volume: 0.45,
      notes: [
        // Bar 1-2: Pumping eighth-note bass
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: 'B3', duration: '8n' },
        { pitch: 'E2', duration: '4n' },

        // Bar 3-4
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'F#3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'F#3', duration: '8n' },
        { pitch: 'E2', duration: '4n' },
        { pitch: null, duration: '4n' },

        // Bar 5-6
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: 'B3', duration: '8n' },

        // Bar 7-8
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'B1', duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: 'A1', duration: '8n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: 'B1', duration: '8n' },
        { pitch: 'B2', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'E2', duration: '4n' },

        // Bar 9-10
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'E2', duration: '4n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'D2', duration: '4n' },

        // Bar 11-12
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'C3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'A2', duration: '8n' },
        { pitch: 'A3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'F#3', duration: '8n' },
        { pitch: 'E2', duration: '4n' },

        // Bar 13-14
        { pitch: 'E2', duration: '4n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'G2', duration: '4n' },
        { pitch: 'G3', duration: '8n' },
        { pitch: 'G2', duration: '8n' },
        { pitch: 'B2', duration: '4n' },
        { pitch: 'A2', duration: '4n' },
        { pitch: 'G2', duration: '4n' },
        { pitch: 'E2', duration: '4n' },

        // Bar 15-16
        { pitch: 'D2', duration: '8n' },
        { pitch: 'D3', duration: '8n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'E3', duration: '8n' },
        { pitch: 'F#2', duration: '8n' },
        { pitch: 'F#3', duration: '8n' },
        { pitch: 'G2', duration: '4n' },
        { pitch: 'E2', duration: '8n' },
        { pitch: 'D2', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'B1', duration: '8n' },
        { pitch: 'E2', duration: '2n' },
      ]
    },
    // Percussion - Noise channel (driving beat)
    {
      wave: 'noise',
      volume: 0.3,
      notes: [
        // Fast 4-bar pattern x4 = 16 bars
        // Aggressive kick-snare with double-time hat

        // Bar 1
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 2
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        // Bar 3
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 4 (fill)
        { pitch: 'E4', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: null, duration: '8n' },

        // Bar 5
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 6
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        // Bar 7
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 8 (fill)
        { pitch: 'E4', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: null, duration: '8n' },

        // Bar 9
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 10
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        // Bar 11
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 12 (fill)
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: null, duration: '8n' },

        // Bar 13
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 14
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'G5', duration: '16n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        // Bar 15
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'C2', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        { pitch: 'E4', duration: '8n' },
        { pitch: 'G5', duration: '8n' },
        // Bar 16 (big fill into loop)
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'E4', duration: '16n' },
        { pitch: 'C2', duration: '4n' },
      ]
    }
  ]
}
